"""Drawing types, values and paths that neither implementation was written for."""

from typing import Final, cast

import ssz
from parity.draw import Draw
from parity.wire import MIXED_IN_WORDS, Step

UINT_TYPES: Final = (ssz.Uint8, ssz.Uint16, ssz.Uint32, ssz.Uint64, ssz.Uint128, ssz.Uint256)
"""Every unsigned integer SSZ defines."""

FIELD_NAMES: Final = ("alpha", "bravo", "charlie")
"""Field names to draw from, fixed so that two runs name the same shape alike."""

MAX_ELEMENTS: Final = 5
"""Elements a generated sequence holds at most, kept small so a case stays readable."""

MAX_WIDTH: Final = 40
"""Bytes or bits a generated byte array or bitfield holds at most."""

MAX_DEPTH: Final = 2
"""Levels a generated type nests, kept small so a shrunk counterexample stays readable."""

MAX_STEPS: Final = 3
"""Steps a generated path takes at most."""

LEAF_KINDS: Final = ("bool", "uint", "byteVector", "byteList", "bitVector", "bitList", "progBits")
"""Shapes holding no type below them, which may be drawn at any depth."""

NESTING_KINDS: Final = ("vector", "list", "progList", "container", "progContainer", "union")
"""Shapes holding a type below them, which may be drawn only while there is room."""


def declare(name: str, base: type[ssz.SSZType], body: dict[str, object]) -> type[ssz.SSZType]:
    """
    Declare a class the way a module would, which is what the model machinery expects.

    A class built here is built at run time, so its identity is stated rather than inferred.
    """
    return cast(
        type[ssz.SSZType],
        type(name, (base,), {"__module__": __name__, "__qualname__": name, **body}),
    )


def build_type(draw: Draw, depth: int = 0) -> type[ssz.SSZType]:
    """A random SSZ type, declared through this implementation like any other."""
    kind = draw.pick(LEAF_KINDS if depth >= MAX_DEPTH else LEAF_KINDS + NESTING_KINDS)

    if kind == "bool":
        return ssz.Boolean
    if kind == "uint":
        return draw.pick(UINT_TYPES)
    if kind == "byteVector":
        return declare("GenBytes", ssz.ByteVector, {"LENGTH": draw.between(1, MAX_WIDTH)})
    if kind == "byteList":
        return declare("GenByteList", ssz.ByteList, {"LIMIT": draw.between(1, MAX_WIDTH)})
    if kind == "bitVector":
        return declare("GenBitVector", ssz.BitVector, {"LENGTH": draw.between(1, MAX_WIDTH)})
    if kind == "bitList":
        return declare("GenBitList", ssz.BitList, {"LIMIT": draw.between(1, MAX_WIDTH)})
    if kind == "progBits":
        return ssz.ProgressiveBitList

    if kind in {"vector", "list", "progList"}:
        element = build_type(draw, depth + 1)
        if kind == "vector":
            # A vector holds at least one element, an empty one naming no tree.
            length = draw.between(1, MAX_ELEMENTS)
            return declare("GenVector", ssz.Vector, {"LENGTH": length, "ELEMENT_TYPE": element})
        if kind == "list":
            limit = draw.between(1, MAX_ELEMENTS)
            return declare("GenList", ssz.List, {"LIMIT": limit, "ELEMENT_TYPE": element})
        return declare("GenProgList", ssz.ProgressiveList, {"ELEMENT_TYPE": element})

    if kind in {"container", "progContainer"}:
        names = list(FIELD_NAMES[: draw.between(1, len(FIELD_NAMES))])
        fields = {name: build_type(draw, depth + 1) for name in names}
        if kind == "container":
            return declare("GenContainer", ssz.Container, {"__annotations__": fields})
        # A layout sets one position per field, and never ends on a gap.
        layout: list[int] = []
        for _ in names:
            layout += [0] * draw.below(3) + [1]
        return declare(
            "GenProgContainer",
            ssz.ProgressiveContainer,
            {"ACTIVE_FIELDS": tuple(layout), "__annotations__": fields},
        )

    # Every option of a union must merkleize alike.
    # One type under several selectors satisfies that without searching for a second.
    option = build_type(draw, depth + 1)
    selectors = draw.pick(([1], [1, 2], [3, 7, 42]))
    return declare("GenUnion", ssz.CompatibleUnion, {"OPTIONS": {s: option for s in selectors}})


def build_value(draw: Draw, ssz_type: type[ssz.SSZType]) -> ssz.SSZType:
    """
    A random value of a type, read off the declaring class.

    Raises:
        AssertionError: A type outside the universe this corpus generates.
    """
    if issubclass(ssz_type, ssz.Boolean):
        return ssz_type(draw.flag())
    if issubclass(ssz_type, ssz.BaseUint):
        # The extremes are drawn often, since that is where an encoding is likeliest to slip.
        top = 2 ** (8 * ssz_type.get_byte_length()) - 1
        return ssz_type(draw.pick([0, 1, top, top // 2, draw.between(0, top)]))
    if issubclass(ssz_type, ssz.ByteVector):
        return ssz_type(bytes(draw.below(256) for _ in range(ssz_type.declared_length())))
    if issubclass(ssz_type, ssz.ByteList):
        count = draw.between(0, ssz_type.declared_limit())
        return ssz_type(data=bytes(draw.below(256) for _ in range(count)))
    if issubclass(ssz_type, ssz.BitVector):
        return ssz_type(data=[draw.flag() for _ in range(ssz_type.declared_length())])
    if issubclass(ssz_type, ssz.ProgressiveBitList):
        return ssz_type(data=[draw.flag() for _ in range(draw.between(0, 2 * MAX_ELEMENTS))])
    if issubclass(ssz_type, ssz.BitList):
        count = draw.between(0, ssz_type.declared_limit())
        return ssz_type(data=[draw.flag() for _ in range(count)])
    if issubclass(ssz_type, ssz.Vector):
        element, length = ssz_type.ELEMENT_TYPE, ssz_type.declared_length()
        return ssz_type(data=[build_value(draw, element) for _ in range(length)])
    if issubclass(ssz_type, ssz.ProgressiveList):
        element = ssz_type.ELEMENT_TYPE
        return ssz_type(data=[build_value(draw, element) for _ in range(draw.below(MAX_ELEMENTS))])
    if issubclass(ssz_type, ssz.List):
        element = ssz_type.ELEMENT_TYPE
        count = draw.between(0, min(ssz_type.declared_limit(), MAX_ELEMENTS))
        return ssz_type(data=[build_value(draw, element) for _ in range(count)])
    if issubclass(ssz_type, (ssz.Container, ssz.ProgressiveContainer)):
        return ssz_type(**{name: build_value(draw, field) for name, field in ssz_type._FIELD_TYPES})
    if issubclass(ssz_type, ssz.CompatibleUnion):
        selector = draw.pick(sorted(ssz_type.OPTIONS))
        chosen = build_value(draw, ssz_type.OPTIONS[selector])
        return ssz_type(selector=ssz.Uint8(selector), data=chosen)
    raise AssertionError(f"no value for {ssz_type.__name__}")


def _mixed_in_word(ssz_type: type[ssz.SSZType]) -> ssz.PathStep | None:
    """The word a type hashes its contents against, where it has one."""
    if issubclass(
        ssz_type, (ssz.List, ssz.ByteList, ssz.BitList, ssz.ProgressiveList, ssz.ProgressiveBitList)
    ):
        return ssz.LENGTH_KEY
    if issubclass(ssz_type, ssz.ProgressiveContainer):
        return ssz.ACTIVE_FIELDS_KEY
    if issubclass(ssz_type, ssz.CompatibleUnion):
        return ssz.SELECTOR_KEY
    return None


def _declared_positions(ssz_type: type[ssz.SSZType]) -> int:
    """Positions a bounded shape declares, whether or not a value fills them."""
    return ssz_type.LENGTH if ssz_type.LENGTH is not None else ssz_type.declared_limit()


type Descent = tuple[Step, type[ssz.SSZType] | None, ssz.SSZType | None] | None
"""One step into a type, and what lies below it where the value reaches that far."""


def _descend(draw: Draw, ssz_type: type[ssz.SSZType], value: ssz.SSZType) -> Descent:
    """
    One step into a type, with the value followed alongside where it reaches.

    A step whose value cannot be followed still names a node, so it ends the path.
    """
    if issubclass(ssz_type, ssz.CompatibleUnion) and isinstance(value, ssz.CompatibleUnion):
        selector = draw.pick(sorted(ssz_type.OPTIONS))
        step = Step(python=selector, lean=selector)
        # Every option shares one subtree.
        # A step onto one the value does not hold still names a node, with nothing below.
        if selector != int(value.selector):
            return step, None, None
        return step, ssz_type.OPTIONS[selector], value.data
    if issubclass(ssz_type, (ssz.Container, ssz.ProgressiveContainer)):
        ordinal = draw.below(len(ssz_type._FIELD_TYPES))
        name, field_type = ssz_type._FIELD_TYPES[ordinal]
        return Step(python=name, lean=ordinal), field_type, getattr(value, name)
    # A byte array or a bitfield holds basic elements, so a step into one ends the path.
    if issubclass(ssz_type, (ssz.ByteVector, ssz.ByteList, ssz.BitVector, ssz.BitList)):
        position = draw.below(_declared_positions(ssz_type))
        return Step(python=position, lean=position), None, None
    if issubclass(ssz_type, ssz.ProgressiveBitList) and isinstance(value, ssz.SSZCollection):
        position = draw.between(0, len(value))
        return Step(python=position, lean=position), None, None
    if issubclass(ssz_type, ssz.ProgressiveList) and isinstance(value, ssz.SSZCollection):
        # A progressive shape reaches only as far as its data.
        # A step past that is itself a claim, since the specification refuses it.
        position = draw.between(0, len(value))
        step = Step(python=position, lean=position)
        if position >= len(value):
            return step, None, None
        return step, ssz_type.ELEMENT_TYPE, value[position]
    if issubclass(ssz_type, (ssz.Vector, ssz.List)) and isinstance(value, ssz.SSZCollection):
        # A bounded shape declares every position it pads out to.
        # One past the data is addressable all the same, merkleizing as a zero leaf.
        position = draw.below(_declared_positions(ssz_type))
        step = Step(python=position, lean=position)
        if position >= len(value):
            return step, None, None
        return step, ssz_type.ELEMENT_TYPE, value[position]
    return None


def build_path(draw: Draw, ssz_type: type[ssz.SSZType], value: ssz.SSZType) -> list[Step]:
    """A random path into a type, in both spellings, ending where it can go no further."""
    steps: list[Step] = []
    current, holder = ssz_type, value
    for _ in range(draw.between(1, MAX_STEPS)):
        # A basic value is one leaf, with nothing inside it to address.
        if issubclass(current, (ssz.BaseUint, ssz.Boolean)):
            break
        # A mixed-in word is one leaf too, and it ends the path that names it.
        word = _mixed_in_word(current)
        if word is not None and draw.below(4) == 0:
            steps.append(Step(python=word, lean=MIXED_IN_WORDS[word]))
            break
        descended = _descend(draw, current, holder)
        if descended is None:
            break
        step, nested_type, nested_value = descended
        steps.append(step)
        if nested_type is None or nested_value is None:
            break
        current, holder = nested_type, nested_value
    return steps
